version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@1.0.29
  slack: circleci/slack@4.12.5

parameters:
  app:
    type: string
    default: "domain-builder"
  alerts_channel:
    type: string
    default: "dpr_cicd_alerts"
  approval_channel:
    type: string
    default: "dpr_cicd_approvals"
  release_ready:
    type: boolean
    default: true
    description: When true, Releases artifacts to Live
  notify_slack:
    type: boolean
    default: true
    description: Send notifications to Slack
  notify_jira:
    type: boolean
    default: true
    description: Send notifications to Associated Jira
  deploy_to_test:
    type: boolean
    default: true
    description: Deploy to Test Environment
  deploy_to_preprod:
    type: boolean
    default: true
    description: Deploy to PreProd Environment
  refresh_lambda:
    type: boolean
    default: true
    description: Refresh Backend Lambda Code  
  refresh_function:
    type: string
    default: "dpr-domain-builder-backend-api-function"
    description: Domain Builder Lambda Code to Refresh 

workflows:
  checkout-build-release:
    jobs:
      - reporting/gradle_build_publish:
          app: << pipeline.parameters.app >>
          app_artifacts_directory: build/libs/
          bucket_prefix: dpr-artifact-store
          deploy_to_test: << pipeline.parameters.deploy_to_test >>
          deploy_to_preprod: << pipeline.parameters.deploy_to_preprod >>
          cache_key: "dpr-domain-builder-build-cache-v4"
          refresh_lambda: << pipeline.parameters.refresh_lambda >>
          refresh_function: << pipeline.parameters.refresh_function >>          
          notify_jira: << pipeline.parameters.notify_jira >>
          notify_slack: << pipeline.parameters.notify_slack >>
          channel: << pipeline.parameters.alerts_channel >>
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
      - slack/on-hold:
          channel: << pipeline.parameters.approval_channel >>
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
          requires: [reporting/gradle_build_publish]
          context:
            - hmpps-reporting-common
      - pause_workflow:
          channel: << pipeline.parameters.approval_channel >>
          type: approval
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
          requires: [slack/on-hold]
          context:
            - hmpps-reporting-common
      - reporting/gradle_promote_live:
          app: << pipeline.parameters.app >>
          release_ready: << pipeline.parameters.release_ready >>
          refresh_lambda: << pipeline.parameters.refresh_lambda >>
          refresh_function: << pipeline.parameters.refresh_function >>          
          notify_slack: << pipeline.parameters.notify_slack >>
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
          requires: [pause_workflow]
          context:
            - hmpps-reporting-common

  owasp-security:
    triggers:
      - schedule:
          cron: "30 6 * * *" ## Runs everyday at 7.30 AM UK TIME
          filters:
            branches:
              only:
                - main
    jobs:
      - reporting/gradle_owasp_check:
          notify_slack: true
          channel: << pipeline.parameters.alerts_channel >>
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          cache_key: "dpr-domain-builder-owasp-build-cache-v1"
