version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:64fdce66c97f468bebd980fe525a47662dfb07ae
  slack: circleci/slack@4.12.5

workflows:
  checkout-build-publish:
    jobs:
      - reporting/gradle_build_publish:
          app: domain-builder
          app_artifacts_directory: build/libs/
          bucket_prefix: dpr-artifact-store
          deploy_to_test: true # Deploy to Test Environment
          deploy_to_preprod: true # Deploy to PreProd Environment
          cache_key: "dpr-domain-builder-build-cache-v4"
          notify_jira: true
          notify_slack: true
          channel: dpr_cicd_alerts
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
      - slack/on-hold:
          channel: dpr_cicd_approvals
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
          requires: [reporting/gradle_build_publish]
          context:
            - hmpps-reporting-common          
      - pause_workflow:
          channel: dpr_cicd_approvals
          type: approval
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
          requires: [slack/on-hold]
          context:
            - hmpps-reporting-common          
      - reporting/gradle_promote_live:
          app: digital-prison-reporting-jobs
          release_ready: true
          notify_slack: true
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
          requires: [pause_workflow]
          context:
            - hmpps-reporting-common            

  owasp-security:
    triggers:
      - schedule:
          cron: "30 6 * * *" ## Runs everyday at 7.30 AM UK TIME
          filters:
            branches:
              only:
                - main
    jobs:
      - reporting/gradle_owasp_check:
          notify_slack: true
          channel: dpr_cicd_alerts
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          cache_key: "dpr-domain-builder-owasp-build-cache-v1"
