version: 2.1

orbs:
  hmpps-reporting: ministryofjustice/hmpps-reporting@dev:fcc6d3f312b78f64da47371dbea8bfa7d02fea36

workflows:
  checkout-build-publish:
    jobs:
      - hmpps-reporting/gradle_owasp_check:
          notify_slack: false
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          filters:
            branches:
              only: main
      - hmpps-reporting/gradle_build_publish:
          app: digital-prison-reporting-domain-builder
          app_artifacts_directory: build/libs/
          bucket_prefix: dpr-artifact-store
          notify_jira: false
          notify_slack: false
          channel: dpr_cicd_alerts
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb

  owasp-security:
    triggers:
      - schedule:
          cron: "30 6 * * *" ## Runs everyday at 7.30 AM UK TIME
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps-reporting/gradle_owasp_check:
          notify_slack: false
          channel: dpr_cicd_alerts
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          cache_key: "v4"
