datasources:
  default:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}"
    username: "${POSTGRES_USERNAME}"
    password: "${POSTGRES_PASSWORD}"
    driverClassName: "org.postgresql.Driver"
  preview:
    url: "jdbc:athena:curated"
    driverClassName: "io.burt.athena.AthenaDriver"
    connectionProperties: "region=eu-west-2;workGroup=primary;outputLocation=s3://dpr-357-athena-test"

flyway:
  datasources:
    default:
      enabled: false
    preview:
      enabled: false

endpoints:
  flyway:
    enabled: false
    sensitive: false

auth:
  apiKey: ${DOMAIN_API_KEY}

  preview:
    # The delimiter used between the source name and table name e.g. nomis.offenders
    inputSourceDelimiter: "."
    # The delimiter to use instead (Athena table names are of the form source_table eg. nomis_offenders
    outputSourceDelimiter: "_"
