datasources:
  default:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}"
    username: "${POSTGRES_USERNAME}"
    password: "${POSTGRES_PASSWORD}"
    driverClassName: "org.postgresql.Driver"

flyway:
  datasources:
    default:
      enabled: false

endpoints:
  flyway:
    enabled: false
    sensitive: false

auth:
  apiKey: ${DOMAIN_API_KEY}
