datasources:
  default:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}"
    username: "${POSTGRES_USERNAME}"
    password: "${POSTGRES_PASSWORD}"
    driverClassName: "org.postgresql.Driver"
  preview:
    url: "jdbc:athena:${PREVIEW_DB_NAME}"
    driverClassName: "io.burt.athena.AthenaDriver"
    connectionProperties: "region=eu-west-2;workGroup=${PREVIEW_WORKGROUP};outputLocation=${PREVIEW_S3_LOCATION}"

flyway:
  datasources:
    default:
      enabled: false
    preview:
      enabled: false

endpoints:
  flyway:
    enabled: false
    sensitive: false

auth:
  apiKey: ${DOMAIN_API_KEY}

  preview:
    # The delimiter used between the source name and table name e.g. nomis.offenders
    inputSourceDelimiter: "."
    # The delimiter to use instead (Athena table names are of the form source_table eg. nomis_offenders
    outputSourceDelimiter: "_"

# TODO - add environment variables where necessary
aws:
  region: eu-west-2
  dynamo:
    endpointUrl: https://dynamodb.eu-west-2.amazonaws.com

dpr:
  domainRegistry: dpr-domain-registry-development